apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  high-availability:
    replicas: 1
  version: "1.14.0"
  ingress:
    kourier:
      enabled: true
  config:
    defaults:
      revision-timeout-seconds: "900"
      max-revision-timeout-seconds: "900"
    features:
      kubernetes.podspec-fieldref: "enabled"
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"